pip3 uninstall feature-extract -y
pip3 uninstall graph-construction -y
pip3 uninstall Inductive-Query-Analaysis -y
pip3 uninstall load-balancer -y
pip3 uninstall qpp-features -y
pip3 uninstall qpp-new -y
pip3 uninstall trainer -y
pip3 uninstall utils -y
pip3 uninstall feat-rep -y